// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const cloneElement: typeof import('react')['cloneElement']
  const createContext: typeof import('react')['createContext']
  const createElement: typeof import('react')['createElement']
  const forwardRef: typeof import('react')['forwardRef']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useEffect: typeof import('react')['useEffect']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
}
export {}
